/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author AR_GI
 */
public class PeminjamanForm extends javax.swing.JFrame {
    
    private DefaultTableModel dtm;
    private Connection koneksi;
    private Statement stmt;
    private ResultSet rs;
    
    private void init(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_buku", "root", "");
            stmt = koneksi.createStatement();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Koneksi Gagal","Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * Creates new form PeminjamanForm
     */
    public PeminjamanForm() {
        initComponents();
        showBuku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKodeBuku = new java.awt.Label();
        labelNamaBuku = new java.awt.Label();
        labelPeminjam = new java.awt.Label();
        labelTanggalPinjam = new java.awt.Label();
        labelTanggalBalik = new java.awt.Label();
        jTextFieldKodebuku = new javax.swing.JTextField();
        jTextFieldNamaBuku = new javax.swing.JTextField();
        jTextFieldPeminjam = new javax.swing.JTextField();
        jTextFieldTanggalPinjam = new javax.swing.JTextField();
        jTextFieldTanggalBalik = new javax.swing.JTextField();
        jButtonPinjam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBuku = new javax.swing.JTable();
        labelNama = new java.awt.Label();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peminjaman");
        setResizable(false);

        labelKodeBuku.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelKodeBuku.setText("Kode Buku");

        labelNamaBuku.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelNamaBuku.setText("Nama Buku");

        labelPeminjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelPeminjam.setText("Nama Peminjam");

        labelTanggalPinjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelTanggalPinjam.setText("Tanggal Pinjam");

        labelTanggalBalik.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelTanggalBalik.setText("Tanggal Pengembalian");

        jTextFieldKodebuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKodebukuActionPerformed(evt);
            }
        });

        jTextFieldNamaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaBukuActionPerformed(evt);
            }
        });

        jTextFieldPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeminjamActionPerformed(evt);
            }
        });

        jTextFieldTanggalPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTanggalPinjamActionPerformed(evt);
            }
        });

        jTextFieldTanggalBalik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTanggalBalikActionPerformed(evt);
            }
        });

        jButtonPinjam.setText("Pinjam");
        jButtonPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPinjamActionPerformed(evt);
            }
        });

        jTableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Nama Buku", "Nama Peminjam", "Tanggal Pinjam", "Tanggal Pengembalian"
            }
        ));
        jScrollPane1.setViewportView(jTableBuku);

        labelNama.setText("1800066 - Muhammad Argi Nafisa");

        jButtonBack.setText("Kembali");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTanggalBalik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPinjam)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldKodebuku)
                            .addComponent(jTextFieldNamaBuku)
                            .addComponent(jTextFieldPeminjam)
                            .addComponent(jTextFieldTanggalPinjam)
                            .addComponent(jTextFieldTanggalBalik, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBack)
                        .addGap(97, 97, 97))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldKodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTanggalBalik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTanggalBalik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonPinjam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void showBuku(){
        
        init();
        Object[] col = {"Kode Buku", "Nama Buku", "Nama Peminjam", "Tanggal Pinjam", "Tanggal Pengembalian"};
        dtm = new DefaultTableModel(null, col);
        jTableBuku.setModel(dtm);
        
        String query = "SELECT * FROM table_buku";
        try{
            rs = stmt.executeQuery(query);
            while(rs.next()){
                String[] row = {rs.getString("kode_buku"), rs.getString("nama_buku"), rs.getString("nama_peminjam"), rs.getString("tanggal_pinjam"), rs.getString("tanggal_pengembalian")};
                dtm.addRow(row);
            }
            koneksi.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    private void jTextFieldKodebukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodebukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKodebukuActionPerformed

    private void jTextFieldNamaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaBukuActionPerformed

    private void jTextFieldPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPeminjamActionPerformed

    private void jTextFieldTanggalPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTanggalPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTanggalPinjamActionPerformed

    private void jTextFieldTanggalBalikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTanggalBalikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTanggalBalikActionPerformed

    private void jButtonPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPinjamActionPerformed
        
        Test t = new Test();
        String kb = jTextFieldKodebuku.getText();
        String nb = jTextFieldNamaBuku.getText();
        String np = jTextFieldPeminjam.getText();
        String tp = jTextFieldTanggalPinjam.getText();
        String tk = jTextFieldTanggalBalik.getText();
        t.insertBuku(kb,nb,np,tp,tk);
        
        jTextFieldKodebuku.requestFocus();
        jTextFieldKodebuku.setText("");
        jTextFieldNamaBuku.setText("");
        jTextFieldPeminjam.setText("");
        jTextFieldTanggalPinjam.setText("");
        jTextFieldTanggalBalik.setText("");
        showBuku();
    }//GEN-LAST:event_jButtonPinjamActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        MainForm main = new MainForm();
        main.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeminjamanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeminjamanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeminjamanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeminjamanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeminjamanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonPinjam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBuku;
    private javax.swing.JTextField jTextFieldKodebuku;
    private javax.swing.JTextField jTextFieldNamaBuku;
    private javax.swing.JTextField jTextFieldPeminjam;
    private javax.swing.JTextField jTextFieldTanggalBalik;
    private javax.swing.JTextField jTextFieldTanggalPinjam;
    private java.awt.Label labelKodeBuku;
    private java.awt.Label labelNama;
    private java.awt.Label labelNamaBuku;
    private java.awt.Label labelPeminjam;
    private java.awt.Label labelTanggalBalik;
    private java.awt.Label labelTanggalPinjam;
    // End of variables declaration//GEN-END:variables
}
